FROM python:3.11

# Add dependencies and install them
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Add rest of application code
COPY ./ /code/
CMD ["uvicorn", "code.order.main:app", "--host", "0.0.0.0", "--port", "80"]
